# preload = ~/Documents/Pictures/Wallpapers/akira-kaneda-bike-night.jpg
# preload = ~/Documents/Pictures/Wallpapers/akira-kaneda-bike-bomb.jpg
#
#
# # wallpaper = ,~/Documents/Pictures/Wallpapers/akira-kaneda-bike-night.jpg
# wallpaper = ,~/Documents/Pictures/Wallpapers/akira-kaneda-bike-bomb.jpg
ipc = on
splash = false

# New 2026 Syntax
wallpaper {
    monitor = 
    path = /home/alex/Documents/Pictures/Wallpapers/akira-kaneda-bike-bomb.jpg
    fit_mode = cover
}
